### PR TITLE
Fix variable reference highlighting

### PR DESCRIPTION
**Pull request by akoeplinger**
This fixes the wrong highlighting when using the following Makefile.am:

```
VARIABLE_A=test.cs
VARIABLE_B=$(VARIABLE_A:.cs=.exe)

test-a:
	echo "hello (world)"

test-b: test-a
	echo hello world
	echo $(VARIABLE_B)
```

It matched the closing bracket in `hello (world)` as the end of the variable assignment.

@maelvalais I'm not really sure this is the right fix, would appreciate any comments :) One interesting thing is that if I switch back to source.makefile2 instead of source.makefile then the matching is correct without my change.

Before:
image

After:

image

### CODE REVIEW

**Comment by maelvalais** [comment]
Dear @akoeplinger,

Welcome and thank you so much for your contribution! It is clean, very well documented. A maintainer dream I guess!

I review the bug and PR asap, thank you again!!

**Comment by maelvalais** [comment]
With your example, I could possibliy want to write
```make
VARIABLE_B=$(VARIABLE_A:.cs=.exe)/some_dir
```

which cannot work with your trick.

To be fair, I don't really know how to get around this issue because in this case `assignment-rhs` can be `$self`. And instead of capturing `$(tab:fooY=%bar)`, `$self` greedily captures another assignment (with the `=` of the  `$(tab:fooY=%bar)`).

Also, I noticed that the Makefile grammar (provided with vscode) is capturing `foobar:tab=abc` as a valid assignment... which seems wrong.

Workaround: use a space after the var name, ie:

```
$(tab: fooY=%bar)
      ^
```

which prevents source.makefile from capturing an assignment... :(

**Comment by akoeplinger** [comment]
Hmm yeah. Any idea why using the source.makefile2 from sublime doesn't show this issue?

**Comment by maelvalais** [comment]
I just tested your idea. You are right, the issue seems to be less of a
problem using source.makefile2 (which I removed from package.json a couple
of weeks ago, thinking that the vscode source.makefile was better but
apparently not so)

We could revert to use source.makefile2 in source.automake then

**Comment by akoeplinger** [comment]
Yeah, switching back to source.makefile2 sounds better in that case.

**Comment by maelvalais** [comment]
wow, took me so much time to propose something
screen shot 2018-03-22 at 17 31 29

Can you test it? On the `better-automake` branch.

```
git fetch --all
git checkout better-automake
```

**Comment by akoeplinger** [comment]
@maelvalais yes, that works much better! I tested it on the original ~2000 line automake file where I found the issue and it seems to work nicely there.

**Comment by maelvalais** [comment]
excellent! I'll push a new version on vscode then


2018-03-22 19:06 GMT+01:00 Alexander Köplinger <notifications@github.com>:

**Comment by akoeplinger** [comment]
Thank you!

**Comment by maelvalais** [comment]
Done! The 0.0.5 has been released :)

**Pull request closed without merging**
